name: Daily Metal Prices Updates

on:
  schedule:
    - cron: '0 17 * * *'

env:
  FIREBASE_URL: ${{ secrets.FIREBASE_URL}}


jobs:
  Daily-Run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependecies
        run: pip install -r requirements.txt

      - name: Create credentials file
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 --decode > credentials.json

      - name: Run App
        run: python main.py